# Generated by Django 4.1 on 2023-09-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("order_num", models.CharField(max_length=100)),
                ("total_expenses", models.FloatField()),
                ("payment", models.CharField(blank=True, max_length=1)),
                ("purchase_datetime", models.DateTimeField(auto_now_add=True)),
                ("crt_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_ord_mng_mdu_order",
                "ordering": ["crt_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("purchase_number", models.IntegerField()),
                ("price", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="app_ord_mng_mdu.order",
                    ),
                ),
            ],
            options={
                "db_table": "app_ord_mng_mdu_item",
                "ordering": ["order", "-purchase_number"],
            },
        ),
    ]
