# Generated by Django 4.1 on 2023-09-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_ord_mng_mdu", "0002_alter_order_options_remove_order_crt_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
    ]
