# Generated by Django 4.1 on 2023-09-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_ord_mng_mdu", "0003_remove_order_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_price",
        ),
    ]
