# Generated by Django 4.1 on 2023-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_ord_mng_mdu", "0004_remove_item_price_remove_item_total_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("username", "order_num")},
        ),
    ]
