# Generated by Django 4.1 on 2023-09-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sin_mng_mdu", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="signinlog",
            unique_together=set(),
        ),
    ]
